ANDLDBR-15: Добавить docker-compose для проекта и CI для деплоя
LadnoDavayteBezRoflov/MyTeam-Backend pull request #1
Opened 2022-03-26 20:02 UTC by TonyBlock

2022-03-26 21:33 UTC, DPeshkoff requested changes

2022-03-26 21:33 UTC, DPeshkoff commented on docker-compose.yml
> +            - TZ=Europe/Moscow
не работает, выпиливай

2022-03-26 21:33 UTC, DPeshkoff commented on docker-compose.yml
> +#            - PUBLIC_DIR=/assets
комментики

2022-03-26 21:33 UTC, DPeshkoff commented on docker-compose.yml
> +#            - /home/ubuntu/01-frontend/dist/assets:/assets
выпиливай

2022-03-27 09:13 UTC, GeorgiyX approved these changes

2022-03-27 09:13 UTC, GeorgiyX commented on Dockerfile
> +CMD /bin/bash -c '$GOPATH/bin/CompileDaemon -log-prefix=false -polling=true -polling-interval=500 -build="go build ./cmd/api/" -command="./api"'
Антон, а точно ли нужен CompileDaemon на проде?
Имхо, он не будет перекомпилировать т.к. сорсы бека скопированы в image при сборке, и не изменяются. Думаю стоит иметь разные Dockerfile для разработки и деплоя:
* В Dockerfile для разработки директорию с сорсами подключать как volume и запускать CompileDaemon.
* В Dockerfile для деплоя копировать соры и один раз их билдить. Можно сделать [multy-stage сборку](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds) (пишут, что размер контейнера будет меньше).

Поправь пожалуйста, если я ошибаюсь.

2022-03-27 10:34 UTC, TonyBlock commented on docker-compose.yml
> +            - TZ=Europe/Moscow
Что именно не работает?

2022-03-27 15:25 UTC, DPeshkoff commented on docker-compose.yml
> +            - TZ=Europe/Moscow
Таймзона здесь бесполезна, у нас не работала 
Да и не нужна она

2022-03-27 15:26 UTC, DPeshkoff commented on Dockerfile
> +CMD /bin/bash -c '$GOPATH/bin/CompileDaemon -log-prefix=false -polling=true -polling-interval=500 -build="go build ./cmd/api/" -command="./api"'
В оригинальном CI на деплой был прописан перезапуск докер-контейнера, эта штука для какой-то внутренней пересборки + переподнятия в случае падения

2022-03-28 21:08 UTC, DPeshkoff requested changes
что за .dev

2022-03-28 21:16 UTC, DPeshkoff approved these changes
поговорили, обсудили, мне ок

2022-03-28 21:16 UTC, merged