ANDLDBR-27: Добавить хэндлеры для users
LadnoDavayteBezRoflov/MyTeam-Backend pull request #6
Opened 2022-04-10 01:06 UTC by DPeshkoff

2022-04-10 19:55 UTC, TonyBlock requested changes

2022-04-10 19:55 UTC, TonyBlock commented on pkg/errors/errors.go
> +	ErrNotFound = errors.New("not found")
Лучше уточнить, кто именно не найден (в данном случае юзер)

2022-04-10 19:55 UTC, TonyBlock commented on app/models/organization.go
> +}
А где привязка к юзеру, который создал организацию?

2022-04-10 19:55 UTC, TonyBlock commented on app/handlers/users.go
> +	c.JSON(http.StatusCreated, gin.H{"status": "successfuly created account"})
думаю, что можно возвращать вообще без тела. c.Status(http.StatusCreated)

2022-04-10 19:55 UTC, TonyBlock commented on app/handlers/users.go
> +	userID, err := userHandler.UserUseCase.CreateUser(user)
Нам предположительно возвращается sessionID

2022-04-10 19:55 UTC, TonyBlock commented on app/usecases/users.go
> +	GetUserByID(userID string) (models.User, error)
Почему userID - строка?

2022-04-10 19:55 UTC, TonyBlock commented on app/usecases/users.go
> +	UpdateUserByID(userID string, user *models.User) (uint, error)
Почему userID - строка?

2022-04-10 19:55 UTC, TonyBlock commented on app/usecases/users.go
> +	GetUserOrganizations(userID string) ([]models.Organization, error)
Почему userID - строка?

2022-04-10 19:55 UTC, TonyBlock commented on app/handlers/users.go
> +	userID := c.Param("userID")
Нам сессионная мидлварь выставляет в случае, если человек залогинен, id текущего юзера. В начале хэндлера необходимо проверять, выставлено ли это значение. Пример обработки есть в удалении сессии, но только для sessionID

2022-04-10 19:55 UTC, TonyBlock commented on app/handlers/users.go
> +	userID := c.Param("userID")
Проверка на результат работы сессионной MW

2022-04-10 19:55 UTC, TonyBlock commented on app/handlers/users.go
> +	userID := c.Param("userID")
Проверка на результат работы сессионной MW

2022-04-10 20:14 UTC, DPeshkoff commented on pkg/errors/errors.go
> +	ErrNotFound = errors.New("not found")
это общай ошибка, зачем? там и так понятно по запросу

2022-04-10 20:16 UTC, DPeshkoff commented on app/models/organization.go
> +}
в юзкейсе добавим, ты в апишку не внес же)

2022-04-10 20:16 UTC, DPeshkoff commented on app/handlers/users.go
> +	c.JSON(http.StatusCreated, gin.H{"status": "successfuly created account"})
плохо, вспомни слова из прошлого семестра про консистентность ответов апишки

2022-04-10 20:19 UTC, DPeshkoff commented on app/handlers/users.go
> +	userID, err := userHandler.UserUseCase.CreateUser(user)
нет, это создание юзера, сессия создается ниже, здесь еще нет никакой sessionID

2022-04-10 20:19 UTC, DPeshkoff commented on app/usecases/users.go
> +	GetUserByID(userID string) (models.User, error)
для чего ей здесь быть числом? здесь это аргумент из строки, который по умолчанию строка

2022-04-10 20:20 UTC, TonyBlock commented on app/models/organization.go
> +}
В апишке нет, но есть в схеме бд

2022-04-10 20:24 UTC, TonyBlock commented on app/handlers/users.go
> +	userID, err := userHandler.UserUseCase.CreateUser(user)
Сессия не создается ниже. Все, что делает CreateSessionCookie - просто возвращает куку с указанным токеном. Предполагается, что в рамках юзкейса по созданию юзера он не только будет создан, но и будет вызвана сессионная репа, которая сохранит сессию

2022-04-10 20:46 UTC, TonyBlock approved these changes

2022-04-13 20:52 UTC, GeorgiyX approved these changes

2022-04-14 23:15 UTC, merged